name: flutter_mobx_template
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  flutter: ">=3.7.1 <4.0.0"
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Http client
  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1

  # State management:
  mobx: ^2.1.3
  flutter_mobx: ^2.0.6+5
  get_it: ^7.2.0
  intl: ^0.18.0

  # Data
  json_annotation: ^4.8.0

  # UI:
  lottie: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Env
  flutter_flavorizr: ^2.1.5

  # Lint
  flutter_lints: ^2.0.1
  analyzer: ^5.4.0

  # Data
  build_runner: ^2.3.3
  json_serializable: ^6.6.0
  mobx_codegen: ^2.1.1

  # Test
  mockito: ^5.3.2
  faker: ^2.1.0
  http_mock_adapter: ^0.3.3

dependency_overrides:
  collection: ^1.17.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/lotties/

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:
  ide: idea
  instructions:
    - assets:download
    - assets:extract
    - android:androidManifest
    - android:buildGradle
    - flutter:flavors
    - flutter:app
    - flutter:targets
    - ios:xcconfig
    - ios:buildTargets
    - ios:schema
    - ios:plist
    - assets:clean
    - ide:config

  flavors:
    dev:
      app:
        name: "SecretWall dev"
      android:
        applicationId: "com.example.flutter_mobx_template.dev"
      ios:
        bundleId: "com.example.flutter_mobx_template.dev"
    qa:
      app:
        name: "SecretWall qa"
      android:
        applicationId: "com.example.flutter_mobx_template.qa"
      ios:
        bundleId: "com.example.flutter_mobx_template.qa"
    prod:
      app:
        name: "SecretWall"
      android:
        applicationId: "com.example.flutter_mobx_template"
      ios:
        bundleId: "com.example.flutter_mobx_template"